name: Docker publish ARM
 
on:
  push:
    paths:
    - '.github/workflows/docker-publish-arm.yml'
env:
  IMAGE_NAME: mydyndns-client

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
          install: true

    - name: Available platforms
      run: |
        echo ${{ steps.buildx.outputs.platforms }}

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build image (ARM32)
      run: |
        docker buildx build \
        --platform "linux/arm/v7" \
        --tag $IMAGE_NAME-arm32 \
        --file "MyDynDns.Client/Dockerfile.arm32" \
        --load .
 
    - name: Docker logout
      run: docker logout