name: Docker publish ARM
 
on:
  push:
    paths:
    - '.github/workflows/docker-publish-arm.yml'
env:
  IMAGE_NAME: mydyndns-client

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
          install: true

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Build image (ARM32)
      run: docker build . --file "MyDynDns.Client/Dockerfile.arm32" --tag mydyndns:latest-arm32
  
    - name: Docker push
      run: |
          docker tag mydyndns:latest-arm32 ${{ secrets.DOCKER_USERNAME }}/mydyndns:latest-arm32
          docker push ${{ secrets.DOCKER_USERNAME }}/mydyndns:latest-arm32
 
    - name: Docker logout
      run: docker logout